version: "3.9"
name: "runner"

services:
  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  api:
    container_name: api
    image: localhost:5000/ole-ya/api
    depends_on:
      - db
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      BASE_URL: ${BASE_URL}
      PAGE_SIZE: ${PAGE_SIZE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: storage
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
  ui:
    container_name: ui
    image: localhost:5000/ole-ya/ui
    depends_on:
      - api
    ports:
      - "8080:80"
  processor:
    container_name: processor
    image: localhost:5000/ole-ya/processor
    depends_on:
      - db
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      BASE_URL: ${BASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: storage
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
