version: "3.9"
name: "runner"

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8888:80"
  api:
    container_name: api
    image: ole-ya/api
    depends_on:
      - db
    ports:
      - "8080:5000"
  processor:
    container_name: processor
    image: ole-ya/processor
    depends_on:
      - db
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - COLLECT_USER_LIMIT=${COLLECT_USER_LIMIT}
      - DAILY_LIKES_LIMIT=${DAILY_LIKES_LIMIT}
      - USER_TO_LIKE=${USER_TO_LIKE}
