version: "3.9"
name: "runner"

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: tinder
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: oleg
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - AUTH_TOKEN=36174a4d-9c5f-4e69-a0ce-d74ba94ad5d6
      - NAME_TO_LIKE=Svetlana
      - PROFILES_TO_CHECK=100
      - PROFILES_TO_LIKE=5
  #      - NAME_TO_LIKE=Diane
  #      - NAME_TO_LIKE=Eli
  #      - NAME_TO_LIKE=MICHAELA
#  pg-admin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=postgres
#    ports:
#      - "8888:80"
#    depends_on:
#      - db
