version: "3.9"
name: "runner"

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  runner:
    image: ole-ya/tinder
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DAILY_LIKES_LIMIT=${DAILY_LIKES_LIMIT}
