version: "3.9"
name: "runner"

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  # pg-admin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres
  #   ports:
  #     - "8888:80"
  api:
    container_name: api
    image: ole-ya/api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      BASE_URL: ${BASE_URL}
      PAGE_SIZE: ${PAGE_SIZE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: storage
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
  ui:
    container_name: ui
    image: ole-ya/ui
    depends_on:
      - api
    ports:
      - "8080:80"
  processor:
    container_name: processor
    image: ole-ya/processor
    depends_on:
      - db
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      BASE_URL: ${BASE_URL}
      COLLECT_USER_LIMIT: ${COLLECT_USER_LIMIT}
      DAILY_LIKES_LIMIT: ${DAILY_LIKES_LIMIT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: storage
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      USER_TO_LIKE: ${USER_TO_LIKE}
