version: "3.9"
name: "runner"

services:
  db:
    container_name: storage
    image: postgres
    environment:
      POSTGRES_DB: tinder
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: oleg
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - AUTH_TOKEN=42416804-7d6f-45c0-941e-99d049aef4ee
      - NAME_TO_FIND=Svetlana # name to find during batch scan
      - BATCH_FIND_LIMIT=100 # how many profiles to check to find like
      - BATCH_LIKE_LIMIT=10 # how many profiles to like before exiting
  #      - NAME_TO_LIKE=Diane
  #      - NAME_TO_LIKE=Eli
  #      - NAME_TO_LIKE=MICHAELA
#  pg-admin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=oyapparov@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=postgres
#    ports:
#      - "8888:80"
#    depends_on:
#      - db
