# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/actions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/actions.proto\"\x1e\n\x0bLikeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"-\n\tLikeReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2c\n\x07\x41\x63tions\x12*\n\x0cScheduleLike\x12\x0c.LikeRequest\x1a\n.LikeReply\"\x00\x12,\n\x0eUnScheduleLike\x12\x0c.LikeRequest\x1a\n.LikeReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.actions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIKEREQUEST._serialized_start=24
  _LIKEREQUEST._serialized_end=54
  _LIKEREPLY._serialized_start=56
  _LIKEREPLY._serialized_end=101
  _ACTIONS._serialized_start=103
  _ACTIONS._serialized_end=202
# @@protoc_insertion_point(module_scope)
