# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import settings_pb2 as protos_dot_settings__pb2


class SettingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUpdateApiKey = channel.unary_unary(
                '/Settings/AddUpdateApiKey',
                request_serializer=protos_dot_settings__pb2.SettingsRequest.SerializeToString,
                response_deserializer=protos_dot_settings__pb2.SettingsReply.FromString,
                )
        self.AddUpdateBaseUrl = channel.unary_unary(
                '/Settings/AddUpdateBaseUrl',
                request_serializer=protos_dot_settings__pb2.SettingsRequest.SerializeToString,
                response_deserializer=protos_dot_settings__pb2.SettingsReply.FromString,
                )
        self.FetchApiKey = channel.unary_unary(
                '/Settings/FetchApiKey',
                request_serializer=protos_dot_settings__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_settings__pb2.FetchSettingsValueReply.FromString,
                )
        self.FetchBaseUrl = channel.unary_unary(
                '/Settings/FetchBaseUrl',
                request_serializer=protos_dot_settings__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_settings__pb2.FetchSettingsValueReply.FromString,
                )
        self.FetchSettings = channel.unary_unary(
                '/Settings/FetchSettings',
                request_serializer=protos_dot_settings__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_settings__pb2.FetchSettingsReply.FromString,
                )


class SettingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUpdateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUpdateBaseUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchBaseUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUpdateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUpdateApiKey,
                    request_deserializer=protos_dot_settings__pb2.SettingsRequest.FromString,
                    response_serializer=protos_dot_settings__pb2.SettingsReply.SerializeToString,
            ),
            'AddUpdateBaseUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUpdateBaseUrl,
                    request_deserializer=protos_dot_settings__pb2.SettingsRequest.FromString,
                    response_serializer=protos_dot_settings__pb2.SettingsReply.SerializeToString,
            ),
            'FetchApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchApiKey,
                    request_deserializer=protos_dot_settings__pb2.Empty.FromString,
                    response_serializer=protos_dot_settings__pb2.FetchSettingsValueReply.SerializeToString,
            ),
            'FetchBaseUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchBaseUrl,
                    request_deserializer=protos_dot_settings__pb2.Empty.FromString,
                    response_serializer=protos_dot_settings__pb2.FetchSettingsValueReply.SerializeToString,
            ),
            'FetchSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSettings,
                    request_deserializer=protos_dot_settings__pb2.Empty.FromString,
                    response_serializer=protos_dot_settings__pb2.FetchSettingsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Settings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Settings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUpdateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Settings/AddUpdateApiKey',
            protos_dot_settings__pb2.SettingsRequest.SerializeToString,
            protos_dot_settings__pb2.SettingsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUpdateBaseUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Settings/AddUpdateBaseUrl',
            protos_dot_settings__pb2.SettingsRequest.SerializeToString,
            protos_dot_settings__pb2.SettingsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Settings/FetchApiKey',
            protos_dot_settings__pb2.Empty.SerializeToString,
            protos_dot_settings__pb2.FetchSettingsValueReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchBaseUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Settings/FetchBaseUrl',
            protos_dot_settings__pb2.Empty.SerializeToString,
            protos_dot_settings__pb2.FetchSettingsValueReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Settings/FetchSettings',
            protos_dot_settings__pb2.Empty.SerializeToString,
            protos_dot_settings__pb2.FetchSettingsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
